---
development:
  cloud_name: dd8rrkpqy
  api_key: '711473195579958'
  api_secret: QfQpkafv12PoF2noKm_-rX0Zd10
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dd8rrkpqy
  api_key: '711473195579958'
  api_secret: QfQpkafv12PoF2noKm_-rX0Zd10
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dd8rrkpqy
  api_key: '711473195579958'
  api_secret: QfQpkafv12PoF2noKm_-rX0Zd10
  enhance_image_tag: true
  static_image_support: false
